### PR TITLE
ENH: improvement in S1 reader to get domain dims

### PR DESCRIPTION
**Pull request by lbusschaert**
Reads the first file in the S1 directory to get nx and ny (instead of looking for 20150101).
I tested this for S1_sigmaVVSMLAI but I implemented it in all S1 readers.

### CODE REVIEW

**Review by mbechtold — COMMENTED** [review]
Looks great, thanks for eliminating the temporary solution. 
I only suggest that you move the irrigation changes to noahmp36_getirrigationstates.F90 to a separate PR.

**Comment by lbusschaert** [comment]
The irrigation changes weren't supposed to be included here... I am not sure they are ready to be included in the RSDA LIS since Sara used the other version for her paper (or I should add an option to check whether the perturbation bias correction is ON or OFF). 
I'll remove the irrigation commit from this PR today or tomorrow.

**Comment by lbusschaert** [comment]
@mbechtold The irrigation commit has now been reverted, everything should be fine for the S1 reader now.

_Note: I will leave the irrigation module as it is for now. I will wait for the meeting with Christian and Sara to see if I make a PR to correct the irrigation application with perturbation BC._

**Review by gdelannoy — APPROVED** [review]
Looks great! 

Disconnected from this PR, but related to the one on snow DA, just wondering: couldn't we extract the nx and ny also out of the SND files?

**Comment by mbechtold** [comment]
> Looks great!
> 
> Disconnected from this PR, but related to the one on snow DA, just wondering: couldn't we extract the nx and ny also out of the SND files?

@IBrangers : Could you check this option for the SND file reader?

**Pull request merged**
